### ISSUE TITLE
FontManager.getFont 返回null

### ISSUE THREAD

**Issue by shook2012** [alibaba/simpleimage#13]

**Comment by qiyunfei** [comment]
这个你是怎么解决的

**Comment by axmanwang** [comment]
是否是系统平台问题，以及jdk版本，如果是windows，用win32FontManager,或
FontManagerFactory.getInstance()

**Comment by axmanwang** [comment]
是否是系统平台问题，以及jdk版本，如果是windows，用win32FontManager,或
FontManagerFactory.getInstance()
另外你的系统中是否安装了这个字体。
