### ISSUE TITLE
Missing artifact com.alibaba:simpleimage.core:jar:1.2.4

### ISSUE THREAD

**Issue by Jakesd** [alibaba/simpleimage#14]
![image](https://cloud.githubusercontent.com/assets/17646382/19920666/15ad704c-a115-11e6-855b-0ba6c2387608.png)
when I imported  the source code ,I met this problem

**Comment by axmanwang** [comment]
可以下载源码自己编译一下，1.2.4个性了float精度问题。和1.2.3比较一下，只有一处改动。
