### ISSUE TITLE
配置maven仓库，编译失败

### ISSUE THREAD

**Issue by LouisTuo** [alibaba/simpleimage#19]
从https://mvnrepository.com/artifact/com.alibaba/simpleimage/1.2.3导入pom依赖，编译时报错，提示Exception in thread "main" java.lang.NoClassDefFoundError: javax/media/jai/PlanarImage，然后找不到这个jar包，maven仓库找不到这个jar包。各种报错，有谁导入pom文件成功的吗？

**Comment by axmanwang** [comment]
这个包经过几年了，maven移掉它我们也没办法，在csdn可以搜索到这个包
